/// OpenLark Bitable V1 多维表格服务模块
///
/// 提供飞书多维表格V1版本API服务，包括：
/// - 应用管理：创建、复制、更新多维表格
/// - 数据表管理：增删改查数据表
/// - 记录管理：表格记录的CRUD操作
/// - 视图管理：表格视图的创建和管理
/// - 字段管理：表格字段类型和属性
/// - 角色管理：自定义角色和协作者权限
/// - 工作流管理：自动化流程配置
use openlark_core::config::Config;

// 应用级别API
pub mod app;

// 应用子模块API
// app 模块显式导出
pub use app::{
    App,
    AppSettings,
    AttachmentInfo,
    AutoNumberInfo,
    BatchCreateRecordRequest,
    BatchCreateRecordResponse,
    BatchCreateRoleMemberRequest,
    BatchCreateRoleMemberResponse,
    BatchCreateTableRequest,
    BatchCreateTableResponse,
    BatchDeleteRecordRequest,
    BatchDeleteRecordResponse,
    BatchDeleteRoleMemberRequest,
    BatchDeleteRoleMemberResponse,
    BatchDeleteTableRequest,
    BatchDeleteTableResponse,
    BatchGetRecordRequest,
    BatchGetRecordResponse,
    BatchUpdateRecordRequest,
    BatchUpdateRecordResponse,
    BlockRole,
    CopyAppRequest,
    CopyAppResponse,
    CopyDashboardRequest,
    CopyDashboardRequestBuilder,
    CopyDashboardResponse,
    CreateAppRequest,
    CreateAppResponse,
    CreateAppRoleRequest,
    CreateAppRoleRequestBody,
    CreateAppRoleResponse,
    CreateFieldRequest,
    CreateFieldResponse,
    CreateRecordItem,
    CreateRecordRequest,
    CreateRecordResponse,
    CreateRoleMemberRequest,
    CreateRoleMemberResponse,
    CreateTableRequest,
    CreateTableResponse,
    CreateViewData,
    CreateViewRequest,
    CreateViewResponse,
    DeleteAppResponse,
    DeleteAppRoleRequest,
    DeleteAppRoleRequestBuilder,
    DeleteAppRoleResponse,
    DeleteFieldRequest,
    DeleteFieldResponse,
    DeleteRecordRequest,
    DeleteRecordRequestBuilder,
    DeleteRecordResponse,
    DeleteRoleMemberRequest,
    DeleteRoleMemberResponse,
    DeleteTableRequest,
    DeleteTableResponse,
    DeleteViewRequest,
    DeleteViewResponse,
    DeletedRecord,
    Field,
    FieldDescription,
    FieldProperty,
    FieldType,
    FilterCondition,
    FilterInfo,
    Form,
    FormFieldQuestion,
    GetAppRequest,
    GetAppResponse,
    GetFormRequest,
    GetFormResponse,
    GetRecordRequest,
    GetRecordResponse,
    GetViewRequest,
    GetViewResponse,
    KanbanItem,
    LinkInfo,
    ListAppRoleRequest,
    ListAppRoleRequestBuilder,
    ListAppRoleResponse,
    ListDashboardsRequest,
    ListDashboardsRequestBuilder,
    ListDashboardsResponse,
    ListFieldRequest,
    ListFieldResponse,
    ListFormFieldQuestionRequest,
    ListFormFieldQuestionResponse,
    ListRecordRequest,
    ListRecordResponse,
    ListRoleMembersRequest,
    ListRoleMembersRequestBuilder,
    ListRoleMembersResponse,
    ListTablesRequest,
    ListTablesRequestBuilder,
    ListTablesResponse,
    ListViewsRequest,
    ListViewsRequestBuilder,
    ListViewsResponse,
    ListWorkflowRequest,
    ListWorkflowResponse,
    LocationInfo,
    MentionInfo,
    PatchFormFieldQuestionBuilder,
    PatchFormFieldQuestionRequest,
    PatchFormFieldQuestionResponse,
    PatchFormFieldRequest,
    PatchFormRequest,
    PatchFormResponse,
    PatchTableRequest,
    PatchTableResponse,
    PatchViewData,
    PatchViewRequest,
    PatchViewResponse,
    PatchedFormFieldQuestion,
    PeopleInfo,
    Person,
    ProgressInfo,
    Record,
    RecordFieldValue,
    RecordFields,
    RecordFieldsBuilder,
    Role,
    RoleMemberId,
    RoleMemberIdType,
    RoleMemberInfo,
    RoleMemberType,
    SearchRecordRequest,
    SearchRecordRequestBody,
    SearchRecordRequestBuilder,
    SearchRecordResponse,
    SortCondition,
    TableData,
    TableField,
    TableInfo,
    TableRole,
    TextSegment,
    TextStyle,
    UpdateAppRequest,
    UpdateAppResponse,
    UpdateAppRoleRequest,
    UpdateAppRoleRequestBody,
    UpdateAppRoleRequestBuilder,
    UpdateAppRoleResponse,
    UpdateFieldRequest,
    UpdateFieldResponse,
    UpdateRecordItem,
    UpdateRecordRequest,
    UpdateRecordRequestBuilder,
    UpdateRecordResponse,
    UpdateWorkflowBody,
    UpdateWorkflowRequest,
    UpdateWorkflowResponse,
    View,
    Workflow,
    WorkflowStatus,
    add_attachment,
    add_attachments,
    add_bool,
    add_date,
    add_email,
    add_link,
    add_links,
    add_member,
    add_mention,
    add_mentions,
    add_multi_select,
    add_number,
    add_phone,
    add_progress,
    add_progress_with_text,
    add_rating,
    add_rich_text,
    add_select,
    add_text,
    add_url,
    add_user_id,
    add_user_ids,
    app_settings,
    app_token,
    automatic_fields,
    avatar,
    block_id,
    block_roles,
    build,
    client_token,
    copy_app,
    copy_builder,
    create_app,
    create_builder,
    date,
    description,
    display_formula_ref,
    execute,
    execute_with_options,
    fetch_all,
    field_id,
    field_name,
    field_names,
    field_type,
    fields,
    filter,
    folder_token,
    form_id,
    gallery_view,
    gantt_view,
    get_app,
    get_builder,
    grid_view,
    ignore_consistency_check,
    kanban_view,
    member_id,
    member_id_type,
    member_list,
    multi_select,
    name,
    new,
    number,
    page_size,
    page_token,
    payload,
    pre_field_id,
    property,
    record_id,
    record_ids,
    records,
    required,
    role_id,
    role_name,
    shared,
    shared_limit,
    single_select,
    sort,
    status,
    submit_limit_once,
    table,
    table_id,
    table_ids,
    table_roles,
    tables,
    text,
    text_field_as_array,
    time_zone,
    title,
    to_json_value,
    ui_type,
    update_app,
    update_builder,
    user_id_type,
    validate,
    view,
    view_id,
    visible,
    with_default_view_name,
    with_fields,
    with_property,
    with_shared_url,
    with_view_type,
    without_content,
    workflow_id,
};

/// Bitable V1 服务
pub struct BitableV1Service {
    pub config: Config,
}

impl BitableV1Service {
    /// 创建Bitable V1服务
    pub fn new(config: Config) -> Self {
        Self { config }
    }

    /// 获取应用管理服务
    pub fn app(&self) -> app::AppService {
        app::AppService::new(self.config.clone())
    }

    /// 获取配置
    pub fn config(&self) -> &Config {
        &self.config
    }
}
