/// Lingo词条管理模块
///
/// 提供Lingo语言服务词条的创建、更新、删除、查询等功能。
use openlark_core::config::Config;

// 导出具体的API实现
pub mod create;
pub mod delete;
pub mod get;
pub mod highlight;
pub mod list;
pub mod r#match;
pub mod search;
pub mod update;

// 重新导出API函数
// create 模块显式导出
pub use create::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// delete 模块显式导出
pub use delete::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// get 模块显式导出
pub use get::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// highlight 模块显式导出
pub use highlight::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// list 模块显式导出
pub use list::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// match 模块显式导出
pub use r#match::{
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    TermType,
};
// search 模块显式导出
pub use search::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};
// update 模块显式导出
pub use update::{
    ClassificationFilter,
    CreateEntityRequest,
    CreateEntityResp,
    DeleteEntityRequest,
    DeleteEntityResp,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityBody,
    HighlightEntityRequest,
    HighlightEntityResp,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityBody,
    MatchEntityRequest,
    MatchEntityResp,
    MatchInfo,
    Phrase,
    SearchEntityBody,
    SearchEntityRequest,
    SearchEntityResp,
    Span,
    TermType,
    UpdateEntityRequest,
    UpdateEntityResp,
    classification_filter,
    creators,
    execute,
    execute_with_options,
    new,
    outer_id,
    page_size,
    page_token,
    provider,
    query,
    repo_id,
    sources,
    user_id_type,
};

/// Lingo词条管理服务
#[derive(Debug, Clone)]
pub struct LingoEntityService {
    config: Config,
}

impl LingoEntityService {
    pub fn new(config: Config) -> Self {
        Self { config }
    }

    /// 获取配置引用
    pub fn config(&self) -> &Config {
        &self.config
    }
}

impl Default for LingoEntityService {
    fn default() -> Self {
        Self::new(Config::default())
    }
}
