//! # 获取群分享链接,
//!,
//! 生成或获取群聊的分享链接。,
//! ,
//! ## 实现状态,
//! ,
//! 🚧 **待实现** - 此功能尚未实现，敬请期待。,
/// # API文档,
    ///,
/// https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/chat-announcement/get,
