//! # 设置群置顶,
//!,
//! 在群聊中置顶一条消息或公告。,
//! ,
//! ## 实现状态,
//! ,
//! 🚧 **待实现** - 此功能尚未实现，敬请期待。,
/// # API文档,
    ///,
/// https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/chat-announcement/get,
