//! # 搜索群聊,
//!,
//! 搜索用户可访问的群聊列表。,
//! ,
//! ## 实现状态,
//! ,
//! 🚧 **待实现** - 此功能尚未实现，敬请期待。,
/// # API文档,
    ///,
/// https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/job_publish_record/search,
