###############################
# cargo-deny 配置
###############################

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
]
exceptions = []
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
]

