/// close 子模块。
pub mod close;
/// combined_create 子模块。
pub mod combined_create;
/// combined_update 子模块。
pub mod combined_update;
/// config 子模块。
pub mod config;
/// get 子模块。
pub mod get;
/// get_detail 子模块。
pub mod get_detail;
/// list 子模块。
pub mod list;
/// manager 子模块。
pub mod manager;
/// open 子模块。
pub mod open;
/// recruiter 子模块。
pub mod recruiter;
/// update_config 子模块。
pub mod update_config;
