/// ccm/docx模块 - 文档块内容管理
///
/// 按照bizTag/project/version/resource/name.rs模式组织
/// 包含chat公告和document操作的相关API
/// 数据模型定义（模型，不算 API）
pub mod documents;
pub mod models;
pub mod v1;

// 使用通配符导出所有子模块
// models 模块显式导出
pub use models::{
    BatchDeleteBlocksRequest,
    BatchDeleteBlocksResponse,
    BatchOperationResult,
    BatchUpdateBlocksRequest,
    BatchUpdateBlocksResponse,
    BlockContent,
    BlockInfo,
    BlockItem,
    BlockUpdate,
    CreateBlockRequest,
    CreateBlockResponse,
    CreateDocumentRequest,
    CreateDocumentResponse,
    DeleteBlockRequest,
    DeleteBlockResponse,
    DocumentBasicInfo,
    DocumentInfo,
    DocumentItem,
    DocumentMetaItem,
    DocumentPermissions,
    DocumentStatistics,
    DocxBlock,
    DocxBlockPage,
    FailedItem,
    FolderInfo,
    GetBlockRequest,
    GetBlockResponse,
    GetDocMetaRequest,
    GetDocMetaResponse,
    GetDocumentRequest,
    GetDocumentResponse,
    GetRawContentRequest,
    GetRawContentResponse,
    ListBlocksRequest,
    ListBlocksResponse,
    PageData,
    Paragraph,
    RichText,
    SearchDocsRequest,
    SearchDocsResponse,
    SearchScope,
    SortDirection,
    SortRule,
    TextElement,
    TextRun,
    TextStyle,
    UpdateBlockRequest,
    UpdateBlockResponse,
    UserInfo,
};
// v1 模块显式导出
pub use v1::{
    BatchDeleteChatAnnouncementBlockChildrenParams,
    BatchDeleteChatAnnouncementBlockChildrenRequest,
    BatchDeleteChatAnnouncementBlockChildrenResponse,
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateChatAnnouncementBlocksParams,
    BatchUpdateChatAnnouncementBlocksRequest,
    BatchUpdateChatAnnouncementBlocksResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    ContentType,
    ConvertContentToBlocksParams,
    ConvertContentToBlocksRequest,
    ConvertContentToBlocksResponse,
    CreateChatAnnouncementBlockChildrenParams,
    CreateChatAnnouncementBlockChildrenRequest,
    CreateChatAnnouncementBlockChildrenResponse,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    CreateDocumentRequest,
    CreateDocumentResponse,
    CreatedDocument,
    Document,
    DocumentCover,
    DocumentDisplaySetting,
    GetChatAnnouncementBlockChildrenParams,
    GetChatAnnouncementBlockChildrenRequest,
    GetChatAnnouncementBlockChildrenResponse,
    GetChatAnnouncementBlockParams,
    GetChatAnnouncementBlockRequest,
    GetChatAnnouncementBlockResponse,
    GetChatAnnouncementBlocksParams,
    GetChatAnnouncementBlocksRequest,
    GetChatAnnouncementBlocksResponse,
    GetChatAnnouncementRequest,
    GetChatAnnouncementResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    GetDocumentRawContentParams,
    GetDocumentRawContentRequest,
    GetDocumentRawContentResponse,
    GetDocumentRequest,
    GetDocumentResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
};
