/// 权限管理模块
pub mod member;
pub mod public;

// 重新导出所有API函数
// member 模块显式导出
pub use member::{
    AuthPermissionMemberRequest,
    AuthPermissionMemberResponse,
    BatchCreatePermissionMemberRequest,
    BatchCreatePermissionMemberResponse,
    CreatePermissionMemberRequest,
    CreatePermissionMemberResponse,
    CreatePermissionPublicPasswordRequest,
    CreatePermissionPublicPasswordResponse,
    DeletePermissionMemberRequest,
    DeletePermissionMemberResponse,
    DeletePermissionPublicPasswordRequest,
    DeletePermissionPublicPasswordResponse,
    GetPublicPermissionRequest,
    GetPublicPermissionResponse,
    ListPermissionMembersRequest,
    ListPermissionMembersResponse,
    PatchPublicPermissionRequest,
    PatchPublicPermissionResponse,
    PermissionMember,
    PermissionMemberItem,
    PermissionPublic,
    PermissionPublicRequest,
    TransferOwnerRequest,
    TransferOwnerResponse,
    UpdatePermissionMemberRequest,
    UpdatePermissionMemberResponse,
    UpdatePermissionPublicPasswordRequest,
    UpdatePermissionPublicPasswordResponse,
    execute,
    execute_with_options,
    fields,
    member_kind,
    need_notification,
    new,
    old_owner_perm,
    perm_type,
    remove_old_owner,
    stay_put,
};
// public 模块显式导出
pub use public::{
    AuthPermissionMemberRequest,
    AuthPermissionMemberResponse,
    BatchCreatePermissionMemberRequest,
    BatchCreatePermissionMemberResponse,
    CreatePermissionMemberRequest,
    CreatePermissionMemberResponse,
    CreatePermissionPublicPasswordRequest,
    CreatePermissionPublicPasswordResponse,
    DeletePermissionMemberRequest,
    DeletePermissionMemberResponse,
    DeletePermissionPublicPasswordRequest,
    DeletePermissionPublicPasswordResponse,
    GetPublicPermissionRequest,
    GetPublicPermissionResponse,
    ListPermissionMembersRequest,
    ListPermissionMembersResponse,
    PatchPublicPermissionRequest,
    PatchPublicPermissionResponse,
    PermissionMember,
    PermissionMemberItem,
    PermissionPublic,
    PermissionPublicRequest,
    TransferOwnerRequest,
    TransferOwnerResponse,
    UpdatePermissionMemberRequest,
    UpdatePermissionMemberResponse,
    UpdatePermissionPublicPasswordRequest,
    UpdatePermissionPublicPasswordResponse,
    execute,
    execute_with_options,
    fields,
    member_kind,
    need_notification,
    new,
    old_owner_perm,
    perm_type,
    remove_old_owner,
    stay_put,
};
