/// advertisement 子模块。
pub mod advertisement;
/// agency 子模块。
pub mod agency;
/// application 子模块。
pub mod application;
/// attachment 子模块。
pub mod attachment;
/// background_check_order 子模块。
pub mod background_check_order;
/// diversity_inclusion 子模块。
pub mod diversity_inclusion;
/// eco_account_custom_field 子模块。
pub mod eco_account_custom_field;
/// eco_background_check 子模块。
pub mod eco_background_check;
/// eco_background_check_custom_field 子模块。
pub mod eco_background_check_custom_field;
/// eco_background_check_package 子模块。
pub mod eco_background_check_package;
/// eco_exam 子模块。
pub mod eco_exam;
/// eco_exam_paper 子模块。
pub mod eco_exam_paper;
/// ehr_import_task 子模块。
pub mod ehr_import_task;
/// employee 子模块。
pub mod employee;
/// evaluation 子模块。
pub mod evaluation;
/// evaluation_task 子模块。
pub mod evaluation_task;
/// exam 子模块。
pub mod exam;
/// exam_marking_task 子模块。
pub mod exam_marking_task;
/// external_application 子模块。
pub mod external_application;
/// external_background_check 子模块。
pub mod external_background_check;
/// external_interview 子模块。
pub mod external_interview;
/// external_interview_assessment 子模块。
pub mod external_interview_assessment;
/// external_offer 子模块。
pub mod external_offer;
/// external_referral_reward 子模块。
pub mod external_referral_reward;
/// interview 子模块。
pub mod interview;
/// interview_feedback_form 子模块。
pub mod interview_feedback_form;
/// interview_record 子模块。
pub mod interview_record;
/// interview_registration_schema 子模块。
pub mod interview_registration_schema;
/// interview_round_type 子模块。
pub mod interview_round_type;
/// interview_task 子模块。
pub mod interview_task;
/// interviewer 子模块。
pub mod interviewer;
/// job 子模块。
pub mod job;
/// job_function 子模块。
pub mod job_function;
/// job_process 子模块。
pub mod job_process;
/// job_publish_record 子模块。
pub mod job_publish_record;
/// job_requirement 子模块。
pub mod job_requirement;
/// job_requirement_schema 子模块。
pub mod job_requirement_schema;
/// job_schema 子模块。
pub mod job_schema;
/// job_type 子模块。
pub mod job_type;
/// location 子模块。
pub mod location;
/// minutes 子模块。
pub mod minutes;
/// note 子模块。
pub mod note;
/// offer 子模块。
pub mod offer;
/// offer_application_form 子模块。
pub mod offer_application_form;
/// offer_approval_template 子模块。
pub mod offer_approval_template;
/// offer_custom_field 子模块。
pub mod offer_custom_field;
/// offer_schema 子模块。
pub mod offer_schema;
/// portal_apply_schema 子模块。
pub mod portal_apply_schema;
/// questionnaire 子模块。
pub mod questionnaire;
/// referral 子模块。
pub mod referral;
/// referral_account 子模块。
pub mod referral_account;
/// referral_website 子模块。
pub mod referral_website;
/// registration_schema 子模块。
pub mod registration_schema;
/// resume_source 子模块。
pub mod resume_source;
/// role 子模块。
pub mod role;
/// subject 子模块。
pub mod subject;
/// talent 子模块。
pub mod talent;
/// talent_blocklist 子模块。
pub mod talent_blocklist;
/// talent_folder 子模块。
pub mod talent_folder;
/// talent_object 子模块。
pub mod talent_object;
/// talent_operation_log 子模块。
pub mod talent_operation_log;
/// talent_pool 子模块。
pub mod talent_pool;
/// talent_tag 子模块。
pub mod talent_tag;
/// termination_reason 子模块。
pub mod termination_reason;
/// test 子模块。
pub mod test;
/// todo 子模块。
pub mod todo;
/// tripartite_agreement 子模块。
pub mod tripartite_agreement;
/// user_role 子模块。
pub mod user_role;
/// website 子模块。
pub mod website;
