#[cfg(feature = "attendance")]
pub mod attendance;
#[cfg(feature = "compensation")]
pub mod compensation_management;
#[cfg(feature = "ehr")]
pub mod ehr;
#[cfg(feature = "corehr")]
pub mod feishu_people;
#[cfg(feature = "hire")]
pub mod hire;
#[cfg(feature = "okr")]
pub mod okr;
#[cfg(feature = "payroll")]
pub mod payroll;
#[cfg(feature = "performance")]
pub mod performance;
