/// bank 子模块。
pub mod bank;
/// bank_branch 子模块。
pub mod bank_branch;
/// city 子模块。
pub mod city;
/// country_region 子模块。
pub mod country_region;
/// country_region_subdivision 子模块。
pub mod country_region_subdivision;
/// currency 子模块。
pub mod currency;
/// district 子模块。
pub mod district;
/// language 子模块。
pub mod language;
/// nationality 子模块。
pub mod nationality;
/// time_zone 子模块。
pub mod time_zone;
