/// approval_groups 子模块。
pub mod approval_groups;
/// approver 子模块。
pub mod approver;
/// basic_info 子模块。
pub mod basic_info;
/// bp 子模块。
pub mod bp;
/// company 子模块。
pub mod company;
/// contract 子模块。
pub mod contract;
/// cost_allocation 子模块。
pub mod cost_allocation;
/// cost_center 子模块。
pub mod cost_center;
/// custom_org 子模块。
pub mod custom_org;
/// default_cost_center 子模块。
pub mod default_cost_center;
/// department 子模块。
pub mod department;
/// draft 子模块。
pub mod draft;
/// employee 子模块。
pub mod employee;
/// employees 子模块。
pub mod employees;
/// job 子模块。
pub mod job;
/// job_change 子模块。
pub mod job_change;
/// job_family 子模块。
pub mod job_family;
/// job_grade 子模块。
pub mod job_grade;
/// job_level 子模块。
pub mod job_level;
/// location 子模块。
pub mod location;
/// offboarding 子模块。
pub mod offboarding;
/// pathway 子模块。
pub mod pathway;
/// person 子模块。
pub mod person;
/// position 子模块。
pub mod position;
/// pre_hire 子模块。
pub mod pre_hire;
/// probation 子模块。
pub mod probation;
/// process 子模块。
pub mod process;
/// process_revoke 子模块。
pub mod process_revoke;
/// process_withdraw 子模块。
pub mod process_withdraw;
/// report_detail_row 子模块。
pub mod report_detail_row;
/// signature_file 子模块。
pub mod signature_file;
/// signature_node 子模块。
pub mod signature_node;
/// signature_template 子模块。
pub mod signature_template;
/// signature_template_info_with_thumbnail 子模块。
pub mod signature_template_info_with_thumbnail;
/// workforce_plan 子模块。
pub mod workforce_plan;
/// workforce_plan_detail 子模块。
pub mod workforce_plan_detail;
/// workforce_plan_detail_row 子模块。
pub mod workforce_plan_detail_row;
