/// cancel_onboard 子模块。
pub mod cancel_onboard;
/// create 子模块。
pub mod create;
/// get 子模块。
pub mod get;
/// get_detail 子模块。
pub mod get_detail;
/// interview 子模块。
pub mod interview;
/// list 子模块。
pub mod list;
/// offer 子模块。
pub mod offer;
/// recover 子模块。
pub mod recover;
/// terminate 子模块。
pub mod terminate;
/// transfer_onboard 子模块。
pub mod transfer_onboard;
/// transfer_stage 子模块。
pub mod transfer_stage;
