/// archive 子模块。
pub mod archive;
/// change_reason 子模块。
pub mod change_reason;
/// indicator 子模块。
pub mod indicator;
/// item 子模块。
pub mod item;
/// item_category 子模块。
pub mod item_category;
/// lump_sum_payment 子模块。
pub mod lump_sum_payment;
/// plan 子模块。
pub mod plan;
/// recurring_payment 子模块。
pub mod recurring_payment;
/// social_archive 子模块。
pub mod social_archive;
/// social_archive_adjust_record 子模块。
pub mod social_archive_adjust_record;
/// social_insurance 子模块。
pub mod social_insurance;
/// social_plan 子模块。
pub mod social_plan;
