/// Wiki V2 空间节点模块
pub mod copy;
pub mod create;
pub mod list;
pub mod r#move;
pub mod move_docs_to_wiki;
pub mod update_title;

// 导出所有子模块内容，避免命名冲突
// copy 模块显式导出
pub use copy::{
    CopyWikiSpaceNodeParams,
    CopyWikiSpaceNodeRequest,
    CopyWikiSpaceNodeResponse,
    CreateWikiSpaceNodeParams,
    CreateWikiSpaceNodeRequest,
    CreateWikiSpaceNodeResponse,
    ListWikiSpaceNodesParams,
    ListWikiSpaceNodesRequest,
    ListWikiSpaceNodesResponse,
    MoveDocsToWikiParams,
    MoveDocsToWikiRequest,
    MoveDocsToWikiResponse,
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
    UpdateWikiSpaceNodeTitleParams,
    UpdateWikiSpaceNodeTitleRequest,
    UpdateWikiSpaceNodeTitleResponse,
    execute,
    execute_with_options,
    new,
    node_token,
    obj_token,
    obj_type,
    parent_wiki_token,
    space_id,
};
// create 模块显式导出
pub use create::{
    CopyWikiSpaceNodeParams,
    CopyWikiSpaceNodeRequest,
    CopyWikiSpaceNodeResponse,
    CreateWikiSpaceNodeParams,
    CreateWikiSpaceNodeRequest,
    CreateWikiSpaceNodeResponse,
    ListWikiSpaceNodesParams,
    ListWikiSpaceNodesRequest,
    ListWikiSpaceNodesResponse,
    MoveDocsToWikiParams,
    MoveDocsToWikiRequest,
    MoveDocsToWikiResponse,
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
    UpdateWikiSpaceNodeTitleParams,
    UpdateWikiSpaceNodeTitleRequest,
    UpdateWikiSpaceNodeTitleResponse,
    execute,
    execute_with_options,
    new,
    node_token,
    obj_token,
    obj_type,
    parent_wiki_token,
    space_id,
};
// list 模块显式导出
pub use list::{
    CopyWikiSpaceNodeParams,
    CopyWikiSpaceNodeRequest,
    CopyWikiSpaceNodeResponse,
    CreateWikiSpaceNodeParams,
    CreateWikiSpaceNodeRequest,
    CreateWikiSpaceNodeResponse,
    ListWikiSpaceNodesParams,
    ListWikiSpaceNodesRequest,
    ListWikiSpaceNodesResponse,
    MoveDocsToWikiParams,
    MoveDocsToWikiRequest,
    MoveDocsToWikiResponse,
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
    UpdateWikiSpaceNodeTitleParams,
    UpdateWikiSpaceNodeTitleRequest,
    UpdateWikiSpaceNodeTitleResponse,
    execute,
    execute_with_options,
    new,
    node_token,
    obj_token,
    obj_type,
    parent_wiki_token,
    space_id,
};
// move_docs_to_wiki 模块显式导出
pub use move_docs_to_wiki::{
    CopyWikiSpaceNodeParams,
    CopyWikiSpaceNodeRequest,
    CopyWikiSpaceNodeResponse,
    CreateWikiSpaceNodeParams,
    CreateWikiSpaceNodeRequest,
    CreateWikiSpaceNodeResponse,
    ListWikiSpaceNodesParams,
    ListWikiSpaceNodesRequest,
    ListWikiSpaceNodesResponse,
    MoveDocsToWikiParams,
    MoveDocsToWikiRequest,
    MoveDocsToWikiResponse,
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
    UpdateWikiSpaceNodeTitleParams,
    UpdateWikiSpaceNodeTitleRequest,
    UpdateWikiSpaceNodeTitleResponse,
    execute,
    execute_with_options,
    new,
    node_token,
    obj_token,
    obj_type,
    parent_wiki_token,
    space_id,
};
// move 模块显式导出
pub use r#move::{
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
};
// update_title 模块显式导出
pub use update_title::{
    CopyWikiSpaceNodeParams,
    CopyWikiSpaceNodeRequest,
    CopyWikiSpaceNodeResponse,
    CreateWikiSpaceNodeParams,
    CreateWikiSpaceNodeRequest,
    CreateWikiSpaceNodeResponse,
    ListWikiSpaceNodesParams,
    ListWikiSpaceNodesRequest,
    ListWikiSpaceNodesResponse,
    MoveDocsToWikiParams,
    MoveDocsToWikiRequest,
    MoveDocsToWikiResponse,
    MoveWikiSpaceNodeParams,
    MoveWikiSpaceNodeRequest,
    MoveWikiSpaceNodeResponse,
    UpdateWikiSpaceNodeTitleParams,
    UpdateWikiSpaceNodeTitleRequest,
    UpdateWikiSpaceNodeTitleResponse,
    execute,
    execute_with_options,
    new,
    node_token,
    obj_token,
    obj_type,
    parent_wiki_token,
    space_id,
};
