/// assigned_user 子模块。
pub mod assigned_user;
/// authorization 子模块。
pub mod authorization;
/// common_data 子模块。
pub mod common_data;
/// company 子模块。
pub mod company;
/// compensation_standard 子模块。
pub mod compensation_standard;
/// contract 子模块。
pub mod contract;
/// country_region 子模块。
pub mod country_region;
/// currency 子模块。
pub mod currency;
/// custom_field 子模块。
pub mod custom_field;
/// department 子模块。
pub mod department;
/// employee 子模块。
pub mod employee;
/// employee_type 子模块。
pub mod employee_type;
/// employment 子模块。
pub mod employment;
/// file 子模块。
pub mod file;
/// job 子模块。
pub mod job;
/// job_change 子模块。
pub mod job_change;
/// job_data 子模块。
pub mod job_data;
/// job_family 子模块。
pub mod job_family;
/// job_level 子模块。
pub mod job_level;
/// leave 子模块。
pub mod leave;
/// leave_granting_record 子模块。
pub mod leave_granting_record;
/// location 子模块。
pub mod location;
/// national_id_type 子模块。
pub mod national_id_type;
/// offboarding 子模块。
pub mod offboarding;
/// person 子模块。
pub mod person;
/// pre_hire 子模块。
pub mod pre_hire;
/// process 子模块。
pub mod process;
/// security_group 子模块。
pub mod security_group;
/// subdivision 子模块。
pub mod subdivision;
/// subregion 子模块。
pub mod subregion;
/// transfer_reason 子模块。
pub mod transfer_reason;
/// transfer_type 子模块。
pub mod transfer_type;
/// working_hours_type 子模块。
pub mod working_hours_type;
