/// 筛选视图（spreadsheet.sheet.filter_view）
pub mod condition;
pub mod create;
pub mod delete;
pub mod get;
pub mod patch;
pub mod query;

use serde::{Deserialize, Serialize};

/// 筛选视图
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterView {
    pub filter_view_id: String,
    pub filter_view_name: String,
    pub range: String,
}

// 重新导出所有API函数
// condition 模块显式导出
pub use condition::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
// create 模块显式导出
pub use create::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
// delete 模块显式导出
pub use delete::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
// get 模块显式导出
pub use get::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
// patch 模块显式导出
pub use patch::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
// query 模块显式导出
pub use query::{
    CreateFilterConditionRequest,
    CreateFilterConditionResponse,
    CreateFilterViewRequest,
    CreateFilterViewResponse,
    DeleteFilterConditionResponse,
    DeleteFilterViewResponse,
    GetFilterConditionResponse,
    GetFilterViewResponse,
    QueryFilterConditionsResponse,
    QueryFilterViewsResponse,
    UpdateFilterConditionRequest,
    UpdateFilterConditionResponse,
    UpdateFilterViewRequest,
    UpdateFilterViewResponse,
    create_filter_condition,
    create_filter_condition_with_options,
    create_filter_view,
    create_filter_view_with_options,
    delete_filter_condition,
    delete_filter_condition_with_options,
    delete_filter_view,
    delete_filter_view_with_options,
    get_filter_condition,
    get_filter_condition_with_options,
    get_filter_view,
    get_filter_view_with_options,
    query_filter_conditions,
    query_filter_conditions_with_options,
    query_filter_views,
    query_filter_views_with_options,
    update_filter_condition,
    update_filter_condition_with_options,
    update_filter_view,
    update_filter_view_with_options,
};
