/// block模块 - 文档块操作API
///
/// 按照bizTag/project/version/resource/name.rs模式组织
pub mod batch_update;
pub mod children;
pub mod descendant;
pub mod get;
pub mod list;
pub mod patch;

// batch_update 模块显式导出
pub use batch_update::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
// children 模块显式导出
pub use children::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
// descendant 模块显式导出
pub use descendant::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
// get 模块显式导出
pub use get::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
// list 模块显式导出
pub use list::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
// patch 模块显式导出
pub use patch::{
    BatchDeleteDocumentBlockChildrenParams,
    BatchDeleteDocumentBlockChildrenRequest,
    BatchDeleteDocumentBlockChildrenResponse,
    BatchUpdateDocumentBlocksParams,
    BatchUpdateDocumentBlocksRequest,
    BatchUpdateDocumentBlocksResponse,
    BatchUpdateRequest,
    BlockIdRelation,
    CreateDocumentBlockChildrenParams,
    CreateDocumentBlockChildrenRequest,
    CreateDocumentBlockChildrenResponse,
    CreateDocumentBlockDescendantParams,
    CreateDocumentBlockDescendantRequest,
    CreateDocumentBlockDescendantResponse,
    GetDocumentBlockChildrenParams,
    GetDocumentBlockChildrenRequest,
    GetDocumentBlockChildrenResponse,
    GetDocumentBlockParams,
    GetDocumentBlockRequest,
    GetDocumentBlockResponse,
    GetDocumentBlocksParams,
    GetDocumentBlocksRequest,
    GetDocumentBlocksResponse,
    UpdateDocumentBlockParams,
    UpdateDocumentBlockRequest,
    UpdateDocumentBlockResponse,
    execute,
    execute_with_options,
    new,
};
