/// Baike 模块
pub mod v1;

// 使用通配符导出所有子模块
// v1 模块显式导出
pub use v1::{
    BaikeImage,
    ClassificationFilter,
    ClassificationItem,
    CreateDraftReq,
    CreateDraftRequest,
    CreateDraftResp,
    CreateEntityReq,
    CreateEntityRequest,
    CreateEntityResp,
    DisplayStatus,
    DownloadFileRequest,
    Draft,
    Entity,
    EntityStatistics,
    ExtractEntityReqBody,
    ExtractEntityRequest,
    ExtractEntityResponse,
    ExtractedWord,
    GetEntityRequest,
    GetEntityResp,
    HighlightEntityReqBody,
    HighlightEntityRequest,
    HighlightEntityResponse,
    ListClassificationRequest,
    ListClassificationResponse,
    ListEntityRequest,
    ListEntityResp,
    MatchEntityReq,
    MatchEntityRequest,
    MatchEntityResp,
    MatchEntityResult,
    OuterInfo,
    Phrase,
    Referer,
    RelatedMeta,
    SearchEntityReqBody,
    SearchEntityRequest,
    SearchEntityResponse,
    Span,
    Term,
    UpdateDraftReq,
    UpdateDraftRequest,
    UpdateDraftResp,
    UpdateEntityReq,
    UpdateEntityRequest,
    UpdateEntityResp,
    UploadFileRequest,
    UploadFileResponse,
    UserIdType,
};
